"""Generates expected values for TimeHelperTests.mq5 from the IANA tz database.

This is an independent oracle: it shares no code with TimeHelper.mqh, so if both
agree, the hand-written DST rules in MQL5 match the official ones.

Server clock (OANDA-Prop Trader / FTMO, confirmed 2026-10-02): New York wall
time + 7 hours, i.e. GMT+2 in US winter, GMT+3 in US summer.

Usage: python tests/gen_time_cases.py > tests/TimeHelperCases.mqh
"""
from datetime import datetime, timedelta, timezone
from zoneinfo import ZoneInfo

NY = ZoneInfo("America/New_York")
LONDON = ZoneInfo("Europe/London")
PRAGUE = ZoneInfo("Europe/Prague")
SERVER_MINUS_NY = timedelta(hours=7)

# (server wall time, why it matters)
CASES = [
    ("2026-01-14 12:00", "winter, both standard time"),
    ("2026-03-06 12:00", "Fri before US spring change"),
    ("2026-03-08 08:59", "US spring change, last minute at GMT+2"),
    ("2026-03-08 10:00", "US spring change, first hour at GMT+3"),
    ("2026-03-09 12:00", "US summer / EU winter mismatch starts"),
    ("2026-03-10 01:30", "mismatch: still previous FTMO day"),
    ("2026-03-10 02:00", "mismatch: FTMO day starts 02:00 server"),
    ("2026-03-27 12:00", "Fri, last trading day of spring mismatch"),
    ("2026-03-29 03:59", "UK/EU spring change, one minute before"),
    ("2026-03-29 04:00", "UK/EU spring change, exact"),
    ("2026-03-30 12:00", "Mon after EU spring change, both summer"),
    ("2026-07-15 00:59", "summer: still previous FTMO day"),
    ("2026-07-15 01:00", "summer: FTMO day starts 01:00 server"),
    ("2026-07-15 09:00", "summer: London 07:00 session open"),
    ("2025-10-24 12:00", "Fri before EU autumn change, both summer"),
    ("2025-10-26 03:59", "UK/EU autumn change, one minute before"),
    ("2025-10-26 04:00", "UK/EU autumn change, exact"),
    ("2025-10-27 10:00", "autumn mismatch: London 07:00 session open"),
    ("2025-10-28 01:30", "autumn mismatch: still previous FTMO day"),
    ("2025-10-28 02:00", "autumn mismatch: FTMO day starts 02:00 server"),
    ("2025-10-31 23:00", "autumn mismatch Fri: London 20:00 weekend close"),
    ("2025-11-02 08:59", "US autumn change, last minute at GMT+3"),
    ("2025-11-02 09:00", "US autumn change, first unambiguous GMT+2"),
    ("2025-11-03 12:00", "Mon after US autumn change, both standard"),
    ("2026-01-16 22:00", "winter Fri: London 20:00 weekend close"),
    ("2026-07-17 22:00", "summer Fri: London 20:00 weekend close"),
    ("2026-10-23 12:00", "Fri before 2026 EU autumn change"),
    ("2026-10-26 12:00", "2026 autumn mismatch"),
    ("2026-11-02 12:00", "Mon after 2026 US autumn change"),
]


def server_to_utc(server: datetime) -> datetime:
    ny_wall = (server - SERVER_MINUS_NY).replace(tzinfo=NY)  # fold=0: first occurrence
    return ny_wall.astimezone(timezone.utc)


def utc_to_server(utc: datetime) -> datetime:
    return utc.astimezone(NY).replace(tzinfo=None) + SERVER_MINUS_NY


def ftmo_day_start_server(utc: datetime) -> datetime:
    prague = utc.astimezone(PRAGUE)
    midnight = datetime(prague.year, prague.month, prague.day, tzinfo=PRAGUE)
    return utc_to_server(midnight.astimezone(timezone.utc))


def mql(dt: datetime) -> str:
    return "D'" + dt.strftime("%Y.%m.%d %H:%M") + "'"


def main() -> None:
    print("// Generated by tests/gen_time_cases.py from the IANA tz database. Do not edit.")
    print("// server, expected UTC, London, Prague, FTMO day start (server time), note")
    print("#define TIME_CASE_COUNT %d" % len(CASES))
    print("void LoadTimeCases(TimeCase &c[])")
    print("{")
    print("   ArrayResize(c, TIME_CASE_COUNT);")
    for i, (text, note) in enumerate(CASES):
        server = datetime.strptime(text, "%Y-%m-%d %H:%M")
        utc = server_to_utc(server)
        # Round-trip guards against picking a server time that doesn't exist
        assert utc_to_server(utc) == server, f"server time {text} does not exist"
        london = utc.astimezone(LONDON).replace(tzinfo=None)
        prague = utc.astimezone(PRAGUE).replace(tzinfo=None)
        day = ftmo_day_start_server(utc)
        print(
            f"   c[{i}].server = {mql(server)}; c[{i}].utc = {mql(utc.replace(tzinfo=None))}; "
            f"c[{i}].london = {mql(london)}; c[{i}].prague = {mql(prague)}; "
            f"c[{i}].ftmoDayStart = {mql(day)}; c[{i}].note = \"{note}\";"
        )
    print("}")
    print()
    print_transitions()
    print()
    print_session_cases()


# Session window 07:00 inclusive to 15:00 exclusive, London time, on H1 bar open.
# Each day: the bars either side of both edges, in winter, summer and both mismatch periods.
SESSION_START, SESSION_END = 7, 15
SESSION_DAYS = ["2026-01-14", "2026-07-15", "2026-03-10", "2025-10-27", "2026-10-26"]


def print_session_cases() -> None:
    rows = []
    for day in SESSION_DAYS:
        base = datetime.strptime(day, "%Y-%m-%d")
        for server_hour in range(24):
            server = base + timedelta(hours=server_hour)
            london = server_to_utc(server).astimezone(LONDON)
            if london.hour in (SESSION_START - 1, SESSION_START, SESSION_END - 1, SESSION_END):
                inside = SESSION_START <= london.hour < SESSION_END
                rows.append((server, london.hour, inside))
    print("// London session window %02d:00-%02d:00 (end exclusive) on H1 bar open time" % (SESSION_START, SESSION_END))
    print("#define SESSION_START_HOUR %d" % SESSION_START)
    print("#define SESSION_END_HOUR %d" % SESSION_END)
    print("#define SESSION_CASE_COUNT %d" % len(rows))
    print("void LoadSessionCases(SessionCase &s[])")
    print("{")
    print("   ArrayResize(s, SESSION_CASE_COUNT);")
    for i, (server, hour, inside) in enumerate(rows):
        print(f"   s[{i}].server = {mql(server)}; s[{i}].londonHour = {hour}; s[{i}].inside = {str(inside).lower()};")
    print("}")


def transitions(tz: ZoneInfo, year: int) -> list:
    """UTC instants in the year where the zone's UTC offset changes."""
    out = []
    t = datetime(year, 1, 1, tzinfo=timezone.utc)
    end = datetime(year + 1, 1, 1, tzinfo=timezone.utc)
    prev = t.astimezone(tz).utcoffset()
    while t < end:
        t += timedelta(hours=1)
        off = t.astimezone(tz).utcoffset()
        if off != prev:
            out.append(t.replace(tzinfo=None))
            prev = off
    return out


def print_transitions() -> None:
    years = range(2014, 2033)
    print("// DST start/end instants in UTC: US (New York) and EU (Prague; London is identical)")
    print("#define DST_YEAR_COUNT %d" % len(years))
    print("void LoadDstYears(DstYear &d[])")
    print("{")
    print("   ArrayResize(d, DST_YEAR_COUNT);")
    for i, y in enumerate(years):
        us = transitions(NY, y)
        eu = transitions(PRAGUE, y)
        assert eu == transitions(LONDON, y), f"London and Prague differ in {y}"
        assert len(us) == 2 and len(eu) == 2
        print(
            f"   d[{i}].year = {y}; d[{i}].usStart = {mql(us[0])}; d[{i}].usEnd = {mql(us[1])}; "
            f"d[{i}].euStart = {mql(eu[0])}; d[{i}].euEnd = {mql(eu[1])};"
        )
    print("}")


if __name__ == "__main__":
    main()
