// Generated by tests/gen_time_cases.py from the IANA tz database. Do not edit.
// server, expected UTC, London, Prague, FTMO day start (server time), note
#define TIME_CASE_COUNT 29
void LoadTimeCases(TimeCase &c[])
{
   ArrayResize(c, TIME_CASE_COUNT);
   c[0].server = D'2026.01.14 12:00'; c[0].utc = D'2026.01.14 10:00'; c[0].london = D'2026.01.14 10:00'; c[0].prague = D'2026.01.14 11:00'; c[0].ftmoDayStart = D'2026.01.14 01:00'; c[0].note = "winter, both standard time";
   c[1].server = D'2026.03.06 12:00'; c[1].utc = D'2026.03.06 10:00'; c[1].london = D'2026.03.06 10:00'; c[1].prague = D'2026.03.06 11:00'; c[1].ftmoDayStart = D'2026.03.06 01:00'; c[1].note = "Fri before US spring change";
   c[2].server = D'2026.03.08 08:59'; c[2].utc = D'2026.03.08 06:59'; c[2].london = D'2026.03.08 06:59'; c[2].prague = D'2026.03.08 07:59'; c[2].ftmoDayStart = D'2026.03.08 01:00'; c[2].note = "US spring change, last minute at GMT+2";
   c[3].server = D'2026.03.08 10:00'; c[3].utc = D'2026.03.08 07:00'; c[3].london = D'2026.03.08 07:00'; c[3].prague = D'2026.03.08 08:00'; c[3].ftmoDayStart = D'2026.03.08 01:00'; c[3].note = "US spring change, first hour at GMT+3";
   c[4].server = D'2026.03.09 12:00'; c[4].utc = D'2026.03.09 09:00'; c[4].london = D'2026.03.09 09:00'; c[4].prague = D'2026.03.09 10:00'; c[4].ftmoDayStart = D'2026.03.09 02:00'; c[4].note = "US summer / EU winter mismatch starts";
   c[5].server = D'2026.03.10 01:30'; c[5].utc = D'2026.03.09 22:30'; c[5].london = D'2026.03.09 22:30'; c[5].prague = D'2026.03.09 23:30'; c[5].ftmoDayStart = D'2026.03.09 02:00'; c[5].note = "mismatch: still previous FTMO day";
   c[6].server = D'2026.03.10 02:00'; c[6].utc = D'2026.03.09 23:00'; c[6].london = D'2026.03.09 23:00'; c[6].prague = D'2026.03.10 00:00'; c[6].ftmoDayStart = D'2026.03.10 02:00'; c[6].note = "mismatch: FTMO day starts 02:00 server";
   c[7].server = D'2026.03.27 12:00'; c[7].utc = D'2026.03.27 09:00'; c[7].london = D'2026.03.27 09:00'; c[7].prague = D'2026.03.27 10:00'; c[7].ftmoDayStart = D'2026.03.27 02:00'; c[7].note = "Fri, last trading day of spring mismatch";
   c[8].server = D'2026.03.29 03:59'; c[8].utc = D'2026.03.29 00:59'; c[8].london = D'2026.03.29 00:59'; c[8].prague = D'2026.03.29 01:59'; c[8].ftmoDayStart = D'2026.03.29 02:00'; c[8].note = "UK/EU spring change, one minute before";
   c[9].server = D'2026.03.29 04:00'; c[9].utc = D'2026.03.29 01:00'; c[9].london = D'2026.03.29 02:00'; c[9].prague = D'2026.03.29 03:00'; c[9].ftmoDayStart = D'2026.03.29 02:00'; c[9].note = "UK/EU spring change, exact";
   c[10].server = D'2026.03.30 12:00'; c[10].utc = D'2026.03.30 09:00'; c[10].london = D'2026.03.30 10:00'; c[10].prague = D'2026.03.30 11:00'; c[10].ftmoDayStart = D'2026.03.30 01:00'; c[10].note = "Mon after EU spring change, both summer";
   c[11].server = D'2026.07.15 00:59'; c[11].utc = D'2026.07.14 21:59'; c[11].london = D'2026.07.14 22:59'; c[11].prague = D'2026.07.14 23:59'; c[11].ftmoDayStart = D'2026.07.14 01:00'; c[11].note = "summer: still previous FTMO day";
   c[12].server = D'2026.07.15 01:00'; c[12].utc = D'2026.07.14 22:00'; c[12].london = D'2026.07.14 23:00'; c[12].prague = D'2026.07.15 00:00'; c[12].ftmoDayStart = D'2026.07.15 01:00'; c[12].note = "summer: FTMO day starts 01:00 server";
   c[13].server = D'2026.07.15 09:00'; c[13].utc = D'2026.07.15 06:00'; c[13].london = D'2026.07.15 07:00'; c[13].prague = D'2026.07.15 08:00'; c[13].ftmoDayStart = D'2026.07.15 01:00'; c[13].note = "summer: London 07:00 session open";
   c[14].server = D'2025.10.24 12:00'; c[14].utc = D'2025.10.24 09:00'; c[14].london = D'2025.10.24 10:00'; c[14].prague = D'2025.10.24 11:00'; c[14].ftmoDayStart = D'2025.10.24 01:00'; c[14].note = "Fri before EU autumn change, both summer";
   c[15].server = D'2025.10.26 03:59'; c[15].utc = D'2025.10.26 00:59'; c[15].london = D'2025.10.26 01:59'; c[15].prague = D'2025.10.26 02:59'; c[15].ftmoDayStart = D'2025.10.26 01:00'; c[15].note = "UK/EU autumn change, one minute before";
   c[16].server = D'2025.10.26 04:00'; c[16].utc = D'2025.10.26 01:00'; c[16].london = D'2025.10.26 01:00'; c[16].prague = D'2025.10.26 02:00'; c[16].ftmoDayStart = D'2025.10.26 01:00'; c[16].note = "UK/EU autumn change, exact";
   c[17].server = D'2025.10.27 10:00'; c[17].utc = D'2025.10.27 07:00'; c[17].london = D'2025.10.27 07:00'; c[17].prague = D'2025.10.27 08:00'; c[17].ftmoDayStart = D'2025.10.27 02:00'; c[17].note = "autumn mismatch: London 07:00 session open";
   c[18].server = D'2025.10.28 01:30'; c[18].utc = D'2025.10.27 22:30'; c[18].london = D'2025.10.27 22:30'; c[18].prague = D'2025.10.27 23:30'; c[18].ftmoDayStart = D'2025.10.27 02:00'; c[18].note = "autumn mismatch: still previous FTMO day";
   c[19].server = D'2025.10.28 02:00'; c[19].utc = D'2025.10.27 23:00'; c[19].london = D'2025.10.27 23:00'; c[19].prague = D'2025.10.28 00:00'; c[19].ftmoDayStart = D'2025.10.28 02:00'; c[19].note = "autumn mismatch: FTMO day starts 02:00 server";
   c[20].server = D'2025.10.31 23:00'; c[20].utc = D'2025.10.31 20:00'; c[20].london = D'2025.10.31 20:00'; c[20].prague = D'2025.10.31 21:00'; c[20].ftmoDayStart = D'2025.10.31 02:00'; c[20].note = "autumn mismatch Fri: London 20:00 weekend close";
   c[21].server = D'2025.11.02 08:59'; c[21].utc = D'2025.11.02 05:59'; c[21].london = D'2025.11.02 05:59'; c[21].prague = D'2025.11.02 06:59'; c[21].ftmoDayStart = D'2025.11.02 02:00'; c[21].note = "US autumn change, last minute at GMT+3";
   c[22].server = D'2025.11.02 09:00'; c[22].utc = D'2025.11.02 07:00'; c[22].london = D'2025.11.02 07:00'; c[22].prague = D'2025.11.02 08:00'; c[22].ftmoDayStart = D'2025.11.02 02:00'; c[22].note = "US autumn change, first unambiguous GMT+2";
   c[23].server = D'2025.11.03 12:00'; c[23].utc = D'2025.11.03 10:00'; c[23].london = D'2025.11.03 10:00'; c[23].prague = D'2025.11.03 11:00'; c[23].ftmoDayStart = D'2025.11.03 01:00'; c[23].note = "Mon after US autumn change, both standard";
   c[24].server = D'2026.01.16 22:00'; c[24].utc = D'2026.01.16 20:00'; c[24].london = D'2026.01.16 20:00'; c[24].prague = D'2026.01.16 21:00'; c[24].ftmoDayStart = D'2026.01.16 01:00'; c[24].note = "winter Fri: London 20:00 weekend close";
   c[25].server = D'2026.07.17 22:00'; c[25].utc = D'2026.07.17 19:00'; c[25].london = D'2026.07.17 20:00'; c[25].prague = D'2026.07.17 21:00'; c[25].ftmoDayStart = D'2026.07.17 01:00'; c[25].note = "summer Fri: London 20:00 weekend close";
   c[26].server = D'2026.10.23 12:00'; c[26].utc = D'2026.10.23 09:00'; c[26].london = D'2026.10.23 10:00'; c[26].prague = D'2026.10.23 11:00'; c[26].ftmoDayStart = D'2026.10.23 01:00'; c[26].note = "Fri before 2026 EU autumn change";
   c[27].server = D'2026.10.26 12:00'; c[27].utc = D'2026.10.26 09:00'; c[27].london = D'2026.10.26 09:00'; c[27].prague = D'2026.10.26 10:00'; c[27].ftmoDayStart = D'2026.10.26 02:00'; c[27].note = "2026 autumn mismatch";
   c[28].server = D'2026.11.02 12:00'; c[28].utc = D'2026.11.02 10:00'; c[28].london = D'2026.11.02 10:00'; c[28].prague = D'2026.11.02 11:00'; c[28].ftmoDayStart = D'2026.11.02 01:00'; c[28].note = "Mon after 2026 US autumn change";
}

// DST start/end instants in UTC: US (New York) and EU (Prague; London is identical)
#define DST_YEAR_COUNT 19
void LoadDstYears(DstYear &d[])
{
   ArrayResize(d, DST_YEAR_COUNT);
   d[0].year = 2014; d[0].usStart = D'2014.03.09 07:00'; d[0].usEnd = D'2014.11.02 06:00'; d[0].euStart = D'2014.03.30 01:00'; d[0].euEnd = D'2014.10.26 01:00';
   d[1].year = 2015; d[1].usStart = D'2015.03.08 07:00'; d[1].usEnd = D'2015.11.01 06:00'; d[1].euStart = D'2015.03.29 01:00'; d[1].euEnd = D'2015.10.25 01:00';
   d[2].year = 2016; d[2].usStart = D'2016.03.13 07:00'; d[2].usEnd = D'2016.11.06 06:00'; d[2].euStart = D'2016.03.27 01:00'; d[2].euEnd = D'2016.10.30 01:00';
   d[3].year = 2017; d[3].usStart = D'2017.03.12 07:00'; d[3].usEnd = D'2017.11.05 06:00'; d[3].euStart = D'2017.03.26 01:00'; d[3].euEnd = D'2017.10.29 01:00';
   d[4].year = 2018; d[4].usStart = D'2018.03.11 07:00'; d[4].usEnd = D'2018.11.04 06:00'; d[4].euStart = D'2018.03.25 01:00'; d[4].euEnd = D'2018.10.28 01:00';
   d[5].year = 2019; d[5].usStart = D'2019.03.10 07:00'; d[5].usEnd = D'2019.11.03 06:00'; d[5].euStart = D'2019.03.31 01:00'; d[5].euEnd = D'2019.10.27 01:00';
   d[6].year = 2020; d[6].usStart = D'2020.03.08 07:00'; d[6].usEnd = D'2020.11.01 06:00'; d[6].euStart = D'2020.03.29 01:00'; d[6].euEnd = D'2020.10.25 01:00';
   d[7].year = 2021; d[7].usStart = D'2021.03.14 07:00'; d[7].usEnd = D'2021.11.07 06:00'; d[7].euStart = D'2021.03.28 01:00'; d[7].euEnd = D'2021.10.31 01:00';
   d[8].year = 2022; d[8].usStart = D'2022.03.13 07:00'; d[8].usEnd = D'2022.11.06 06:00'; d[8].euStart = D'2022.03.27 01:00'; d[8].euEnd = D'2022.10.30 01:00';
   d[9].year = 2023; d[9].usStart = D'2023.03.12 07:00'; d[9].usEnd = D'2023.11.05 06:00'; d[9].euStart = D'2023.03.26 01:00'; d[9].euEnd = D'2023.10.29 01:00';
   d[10].year = 2024; d[10].usStart = D'2024.03.10 07:00'; d[10].usEnd = D'2024.11.03 06:00'; d[10].euStart = D'2024.03.31 01:00'; d[10].euEnd = D'2024.10.27 01:00';
   d[11].year = 2025; d[11].usStart = D'2025.03.09 07:00'; d[11].usEnd = D'2025.11.02 06:00'; d[11].euStart = D'2025.03.30 01:00'; d[11].euEnd = D'2025.10.26 01:00';
   d[12].year = 2026; d[12].usStart = D'2026.03.08 07:00'; d[12].usEnd = D'2026.11.01 06:00'; d[12].euStart = D'2026.03.29 01:00'; d[12].euEnd = D'2026.10.25 01:00';
   d[13].year = 2027; d[13].usStart = D'2027.03.14 07:00'; d[13].usEnd = D'2027.11.07 06:00'; d[13].euStart = D'2027.03.28 01:00'; d[13].euEnd = D'2027.10.31 01:00';
   d[14].year = 2028; d[14].usStart = D'2028.03.12 07:00'; d[14].usEnd = D'2028.11.05 06:00'; d[14].euStart = D'2028.03.26 01:00'; d[14].euEnd = D'2028.10.29 01:00';
   d[15].year = 2029; d[15].usStart = D'2029.03.11 07:00'; d[15].usEnd = D'2029.11.04 06:00'; d[15].euStart = D'2029.03.25 01:00'; d[15].euEnd = D'2029.10.28 01:00';
   d[16].year = 2030; d[16].usStart = D'2030.03.10 07:00'; d[16].usEnd = D'2030.11.03 06:00'; d[16].euStart = D'2030.03.31 01:00'; d[16].euEnd = D'2030.10.27 01:00';
   d[17].year = 2031; d[17].usStart = D'2031.03.09 07:00'; d[17].usEnd = D'2031.11.02 06:00'; d[17].euStart = D'2031.03.30 01:00'; d[17].euEnd = D'2031.10.26 01:00';
   d[18].year = 2032; d[18].usStart = D'2032.03.14 07:00'; d[18].usEnd = D'2032.11.07 06:00'; d[18].euStart = D'2032.03.28 01:00'; d[18].euEnd = D'2032.10.31 01:00';
}

// London session window 07:00-15:00 (end exclusive) on H1 bar open time
#define SESSION_START_HOUR 7
#define SESSION_END_HOUR 15
#define SESSION_CASE_COUNT 20
void LoadSessionCases(SessionCase &s[])
{
   ArrayResize(s, SESSION_CASE_COUNT);
   s[0].server = D'2026.01.14 08:00'; s[0].londonHour = 6; s[0].inside = false;
   s[1].server = D'2026.01.14 09:00'; s[1].londonHour = 7; s[1].inside = true;
   s[2].server = D'2026.01.14 16:00'; s[2].londonHour = 14; s[2].inside = true;
   s[3].server = D'2026.01.14 17:00'; s[3].londonHour = 15; s[3].inside = false;
   s[4].server = D'2026.07.15 08:00'; s[4].londonHour = 6; s[4].inside = false;
   s[5].server = D'2026.07.15 09:00'; s[5].londonHour = 7; s[5].inside = true;
   s[6].server = D'2026.07.15 16:00'; s[6].londonHour = 14; s[6].inside = true;
   s[7].server = D'2026.07.15 17:00'; s[7].londonHour = 15; s[7].inside = false;
   s[8].server = D'2026.03.10 09:00'; s[8].londonHour = 6; s[8].inside = false;
   s[9].server = D'2026.03.10 10:00'; s[9].londonHour = 7; s[9].inside = true;
   s[10].server = D'2026.03.10 17:00'; s[10].londonHour = 14; s[10].inside = true;
   s[11].server = D'2026.03.10 18:00'; s[11].londonHour = 15; s[11].inside = false;
   s[12].server = D'2025.10.27 09:00'; s[12].londonHour = 6; s[12].inside = false;
   s[13].server = D'2025.10.27 10:00'; s[13].londonHour = 7; s[13].inside = true;
   s[14].server = D'2025.10.27 17:00'; s[14].londonHour = 14; s[14].inside = true;
   s[15].server = D'2025.10.27 18:00'; s[15].londonHour = 15; s[15].inside = false;
   s[16].server = D'2026.10.26 09:00'; s[16].londonHour = 6; s[16].inside = false;
   s[17].server = D'2026.10.26 10:00'; s[17].londonHour = 7; s[17].inside = true;
   s[18].server = D'2026.10.26 17:00'; s[18].londonHour = 14; s[18].inside = true;
   s[19].server = D'2026.10.26 18:00'; s[19].londonHour = 15; s[19].inside = false;
}
